apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      name: model
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: zakariajaadi/k8s-getting-started:0.0.16
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000
              protocol: TCP

          env:

            - name: PYTHONPATH
              value: "/app/src:/app"

            - name: ENV_MODE
              valueFrom:
                  configMapKeyRef:
                    name: config
                    key: ENV_MODE
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                  configMapKeyRef:
                    name: config
                    key: MLFLOW_TRACKING_URI
            - name: MLFLOW_DB_NAME
              valueFrom:
                  configMapKeyRef:
                    name: config
                    key: MLFLOW_DB_NAME
            - name: MODEL_URI
              valueFrom:
                  configMapKeyRef:
                    name: config
                    key: MODEL_URI
            - name: DB_HOST
              valueFrom:
                  configMapKeyRef:
                    name: config
                    key: DB_HOST
            - name: DB_PORT
              valueFrom:
                  configMapKeyRef:
                    name: config
                    key: DB_PORT
            - name: DB_USER
              valueFrom:
                  secretKeyRef:
                    name: secret
                    key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: secret
                    key: POSTGRES_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MINIO_ROOT_USER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MINIO_ROOT_PASSWORD
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MLFLOW_S3_ENDPOINT_URL
          command: [ "uvicorn" ]
          args: [ "src.model_api:app", "--host", "0.0.0.0", "--port", "8000" ]
      restartPolicy: Always
      