apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: web-ui
      port: 9001
      targetPort: 9001
      nodePort: 32001

  selector:
    app: minio