apiVersion: v1
kind: Service
metadata:
  name: prefect
spec:
  selector:
    app: prefect
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30420
  type: NodePort
  