apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  ##--Postgres--##
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'example'
  PREFECT_DB_CONNECTION_URL: 'postgresql+asyncpg://postgres:example@postgres:5432/prefectdb'
  ##--Minio--##
  MINIO_ROOT_USER: 'minioadmin'
  MINIO_ROOT_PASSWORD: 'minioadmin'
