data:
    bucket: pipelines-data
    raw_data_key: prod/wine_quality_data/raw/data.csv
    train_data_key: prod/wine_quality_data/processed/train.csv
    test_data_key: prod/wine_quality_data/processed/test.csv
    target_name: quality
    test_size: 0.2
    random_state: 42

minio:
    endpoint_url: http://minio:9000
    access_key: ${oc.env:AWS_ACCESS_KEY_ID}
    secret_key: ${oc.env:AWS_SECRET_ACCESS_KEY}

mlflow:
    tracking_uri: http://mlflow:5000
    experiment_name: wine_quality_prod
    registered_model_name: wine_quality_prod
    model_uri: models:/wine_quality_prod@champion
    artifact_root: s3://mlflow-artifacts/

database:
    host: postgres
    port: 5432
    user: ${oc.env:DB_USER}
    password: ${oc.env:DB_PASSWORD}
    monitoring_db_name: monitoring
    mlflow_db_name: mlflowdb
    prefect_db_name: prefectdb

logging:
    level: INFO

